export const imagesLinks = {
  logos: {
    full: '/logo_full.svg',
    full_white: '/logo_white.svg',
    simple: '/logo.svg',
  },
  icons: {
    arrow: '/icons/arrow.svg',
    features: '/icons/features.svg',
    letter: '/icons/letter.svg',
    lightning: '/icons/lightning.svg',
    message: '/icons/message.svg',
    project: '/icons/project.svg',
    new_project: '/icons/new_project.svg',
    saved: '/icons/saved.svg',
    more: '/icons/more.svg',
    caret: '/icons/caret.svg',
    pen: '/icons/pen.svg',
    close: '/icons/close.svg',
    settings: '/icons/settings.svg',
    plan: '/icons/plan.svg',
    team: '/icons/team.svg',
    profile: '/icons/profile.svg',
    bubbles: '/icons/bubbles.svg',
    check: '/icons/check.svg',
    plus_circle: '/icons/plus_circle.svg',
    content_copy: '/icons/content_copy.svg',
    trending_arrow: '/icons/trending_arrow.svg',
    trash: '/icons/trash.svg',
    credits: '/icons/credits.svg',
    sad: '/icons/sad.svg',
    logout: '/icons/logout.svg',
  },
  companies: {
    logo: {
      alma: '/companies/logo_alma.svg',
      blablacar: '/companies/logo_blablacar.svg',
      jobteaser: '/companies/logo_jobteaser.svg',
      payfit: '/companies/logo_payfit.svg',
      swile: '/companies/logo_swile.svg',
    },
  },
  tools: {
    cta: '/tools/cta.svg',
    youtube: '/tools/youtube.svg',
  },
  flags: '/flags',
  gifs: {
    avatar: '/avatar.gif',
  },
};
